# Generated by Django 4.0.4 on 2022-06-27 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto_app', '0002_descripcion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion',
            name='puntuacion',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Usuario_perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='profile_image')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
