# Generated by Django 4.0.4 on 2022-07-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_app', '0002_usuario_perfil_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario_perfil',
            name='email',
        ),
        migrations.AddField(
            model_name='usuario_perfil',
            name='web',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
