# Generated by Django 4.0.4 on 2022-07-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_app', '0005_modificacionesfooter_alter_usuario_perfil_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modificacionesfooter',
            name='direccion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='modificacionesfooter',
            name='telefono',
            field=models.CharField(max_length=200),
        ),
    ]
