# Generated by Django 4.0.4 on 2022-07-04 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_app', '0006_alter_modificacionesfooter_direccion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModificacionesFooter',
        ),
    ]
