# Generated by Django 4.0.4 on 2022-07-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_app', '0007_delete_modificacionesfooter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_perfil',
            name='web',
            field=models.CharField(max_length=300),
        ),
    ]
