# Generated by Django 4.0.4 on 2022-07-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_app', '0008_alter_usuario_perfil_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_perfil',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='usuario_perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario_perfil',
            name='web',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
