# Generated by Django 4.0.4 on 2022-07-05 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_app', '0010_descripcion_imagen_alter_usuario_perfil_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descripcion',
            name='imagen',
        ),
    ]
